CREATE TABLE student (
id                INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
username          VARCHAR(255) NOT NULL,
password          VARCHAR(255) NOT NULL,
email             VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE homework (
id          INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
student_id   INT NOT NULL,
content       VARCHAR(255),
PRIMARY KEY (id)
);


insert into student values(1,'王玉成','123456','wangyc@qq.com');
insert into student values(2,'刘晴晴','654321','liuqq@qq.com');

insert into homework values(1,1,'content1');
insert into homework values(2,2,'content2');